import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FlowbiteInit from "@/components/FlowbiteInit";
import Footer from "@/components/layout/footer";
import Header from "@/components/layout/Header";
import { cookies } from "next/headers";
import { jwtDecode } from "jwt-decode";
import getUserProfile from "@/utils/getUserProfileAction";
import { AuthProvider } from "./context/AuthContext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getInitialUser() {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value;

  if (!token) return null;

  const decodedToken = jwtDecode(token) as { _id: string };

  const userId = decodedToken._id;

  if (!userId) return null;

  const userData = await getUserProfile(userId);
  const result = {
    _id: userData.user._id,
    email: userData.user.email,
    firstName: userData.user.firstName,
    userName: userData.user.userName,
    lastName: userData.user.lastName,
    isAdmin: userData.user.isAdmin,
    phone: userData.user.phone,
  };
  return result;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialUser = await getInitialUser();
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex">
        <ToastContainer position="bottom-right" theme="dark" />{" "}
        <AuthProvider initialUser={initialUser}>
          <FlowbiteInit />
          <main className="grow pt-30">
            <Header />
            <div className="min-h-[60lvh]">{children}</div>
            <Footer />
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
